[theme]
primaryColor = "#76B900"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"

[server]
maxUploadSize = 20
headless = true
enableCORS = false
enableXsrfProtection = true
